### ISSUE TITLE
Build error: no viable conversion

### ISSUE THREAD

**Issue by llamafilm** [HDRWCG/HDRStaticMetadata#2]
When trying to build on macOS 10.13.4, I get the following errors.  I realize the case-sensitive warnings can be ignored, but I don't know how to resolve the errors.  I'm using 

```
$ ./hdrgeneratorbuild.sh 
hdrgenerator.cpp:28:10: warning: non-portable path to file
      '<opencv2/core/core.hpp>'; specified path differs in case from file name
      on disk [-Wnonportable-include-path]
#include <Opencv2/core/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/core/core.hpp>
hdrgenerator.cpp:30:10: warning: non-portable path to file
      '<opencv2/highgui/highgui.hpp>'; specified path differs in case from file
      name on disk [-Wnonportable-include-path]
#include <Opencv2/highgui/highgui.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/highgui/highgui.hpp>
hdrgenerator.cpp:31:10: warning: non-portable path to file
      '<opencv2/imgproc/imgproc.hpp>'; specified path differs in case from file
      name on disk [-Wnonportable-include-path]
#include <Opencv2/imgproc/imgproc.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/imgproc/imgproc.hpp>
hdrgenerator.cpp:106:17: error: no viable conversion from
      'OpenImageIO_v1_9::ImageInput::unique_ptr' (aka
      'unique_ptr<OpenImageIO_v1_9::ImageInput>') to
      'OpenImageIO_v1_9::ImageInput *'
    ImageInput *in = ImageInput::open (path);
                ^    ~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
activedimensions.cpp:17:10: warning: non-portable path to file
      '<opencv2/core/core.hpp>'; specified path differs in case from file name
      on disk [-Wnonportable-include-path]
#include <Opencv2/core/core.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/core/core.hpp>
activedimensions.cpp:19:10: warning: non-portable path to file
      '<opencv2/highgui/highgui.hpp>'; specified path differs in case from file
      name on disk [-Wnonportable-include-path]
#include <Opencv2/highgui/highgui.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/highgui/highgui.hpp>
activedimensions.cpp:20:10: warning: non-portable path to file
      '<opencv2/imgproc/imgproc.hpp>'; specified path differs in case from file
      name on disk [-Wnonportable-include-path]
#include <Opencv2/imgproc/imgproc.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         <opencv2/imgproc/imgproc.hpp>
activedimensions.cpp:40:17: error: no viable conversion from
      'OpenImageIO_v1_9::ImageInput::unique_ptr' (aka
      'unique_ptr<OpenImageIO_v1_9::ImageInput>') to
      'OpenImageIO_v1_9::ImageInput *'
    ImageInput *in = ImageInput::open (filePath);
                ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.

$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by llamafilm** [comment]
It fails similarly in gcc7:
```
$ ./hdrgeneratorbuild.sh 
hdrgenerator.cpp: In function 'HDRMetaDataResult calculateMetadataForPath(const char*, bool, bool, HDRActiveArea)':
hdrgenerator.cpp:106:44: error: cannot convert 'OpenImageIO_v1_9::ImageInput::unique_ptr {aka std::unique_ptr<OpenImageIO_v1_9::ImageInput>}' to 'OpenImageIO_v1_9::ImageInput*' in initialization
     ImageInput *in = ImageInput::open (path);
                                            ^
activedimensions.cpp: In function 'std::pair<int, int> getActiveAreaDimensionsForFilePath(const char*)':
activedimensions.cpp:40:48: error: cannot convert 'OpenImageIO_v1_9::ImageInput::unique_ptr {aka std::unique_ptr<OpenImageIO_v1_9::ImageInput>}' to 'OpenImageIO_v1_9::ImageInput*' in initialization
     ImageInput *in = ImageInput::open (filePath);
                                                ^
$ g++ --version
g++ (MacPorts gcc7 7.3.0_1) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
